name: kisan_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  country_picker: ^2.0.27
  phone_number: ^2.1.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  speech_to_text: ^6.4.0
  image_picker: ^1.0.4
  permission_handler: ^11.3.1
  flutter_tts: ^4.0.2
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.17.8


flutter:
  uses-material-design: true

  assets:
    - assets/images/kisan_image.png
    - assets/images/kisan_logo.png
    - assets/images/farmer.jpg
    - assets/images/truck.jpg
    - assets/images/farmer_icon.png

