// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqvaarXGhE0eRhlzLrgQQmXNeAUkDf9oA',
    appId: '1:247743444691:web:d7cd9200b16b5c0fcd0626',
    messagingSenderId: '247743444691',
    projectId: 'project-kisan-app',
    authDomain: 'project-kisan-app.firebaseapp.com',
    storageBucket: 'project-kisan-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX19Lf5liSOAl8cWBSmzfJ_h-B_sNpNnQ',
    appId: '1:247743444691:android:fb06f86876315d12cd0626',
    messagingSenderId: '247743444691',
    projectId: 'project-kisan-app',
    storageBucket: 'project-kisan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJr1hCxt4UEuQyI8V2lPH5tvHlHNzKZek',
    appId: '1:247743444691:ios:2ce17080d804bff2cd0626',
    messagingSenderId: '247743444691',
    projectId: 'project-kisan-app',
    storageBucket: 'project-kisan-app.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJr1hCxt4UEuQyI8V2lPH5tvHlHNzKZek',
    appId: '1:247743444691:ios:2ce17080d804bff2cd0626',
    messagingSenderId: '247743444691',
    projectId: 'project-kisan-app',
    storageBucket: 'project-kisan-app.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqvaarXGhE0eRhlzLrgQQmXNeAUkDf9oA',
    appId: '1:247743444691:web:a7ac66a2e31b285ecd0626',
    messagingSenderId: '247743444691',
    projectId: 'project-kisan-app',
    authDomain: 'project-kisan-app.firebaseapp.com',
    storageBucket: 'project-kisan-app.firebasestorage.app',
  );
}
